In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  

def linear_svm():
    # download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
    # info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

    # load data
    bankdata = pd.read_csv("D:/255/bill_authentication.csv")  

    # see the data
    bankdata.shape  

    # see head
    bankdata.head()  

    # data processing
    X = bankdata.drop('Class', axis=1)  
    y = bankdata['Class']  

    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='linear')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))  


# Iris dataset  https://archive.ics.uci.edu/ml/datasets/iris4
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  
    return X_train, X_test, y_train, y_test 

def polynomial_kernel(X_train, X_test, y_train, y_test ):
    pass
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='poly')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  
    from sklearn.metrics import accuracy_score
    print("accuracy score for polynomial kernel",accuracy_score(y_test, y_pred))
    from sklearn.metrics import confusion_matrix  
    print("confusion matrix for polynomial kernel",confusion_matrix(y_test, y_pred))  

    # TODO
    # NOTE: use 8-degree in the degree hyperparameter. 
    # Trains, predicts and evaluates the model

def gaussian_kernel(X_train, X_test, y_train, y_test ):
    pass
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='rbf')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  
    from sklearn.metrics import accuracy_score
    print("accuracy score for guassian kernel",accuracy_score(y_test, y_pred))
    from sklearn.metrics import confusion_matrix  
    print("confusion matrix for guassian kernel",confusion_matrix(y_test, y_pred))  
     
    # TODO
    # Trains, predicts and evaluates the model

def sigmoid_kernel(X_train, X_test, y_train, y_test ):
    pass
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='sigmoid')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test) 
    from sklearn.metrics import accuracy_score
    print("accuracy score for sigmoid kernel",accuracy_score(y_test, y_pred))
    from sklearn.metrics import confusion_matrix  
    print("confusion matrix for sigmoid kernel",confusion_matrix(y_test, y_pred)) 
    # TODO
    # Trains, predicts and evaluates the model

def test():
    X_train, X_test, y_train, y_test  = import_iris()
    polynomial_kernel(X_train, X_test, y_train, y_test )
    gaussian_kernel(X_train, X_test, y_train, y_test )
    sigmoid_kernel(X_train, X_test, y_train, y_test )
    
    # NOTE: 3-point extra credit for plotting three kernel models.

    

test()


accuracy score for polynomial kernel 1.0
confusion matrix for polynomial kernel [[ 9  0  0]
 [ 0 11  0]
 [ 0  0 10]]
accuracy score for guassian kernel 0.9666666666666667
confusion matrix for guassian kernel [[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
accuracy score for sigmoid kernel 0.3
confusion matrix for sigmoid kernel [[ 9  0  0]
 [11  0  0]
 [10  0  0]]
